POST http://localhost:3333/camionete
Content-Type: application/json

{
    "cor": "azul",
    "modelo": "maverik",
    "marca": "ford"
}

###

GET http://localhost:3333/camionete
###

GET http://localhost:3333/camionete?search=IFMS

###

PUT http://localhost:3333/camionetes/f43a9a30-83e3-4206-b193-0189e49b5009
Content-Type: application/json

{
    "cor": "branca",
    "modelo": "laramie 2500",
    "marca": "ram"
}

###

DELETE http://localhost:3333/camionetes/
